name: Java Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'   # or 11 / 21 depending on your need
          distribution: 'temurin'

      - name: Compile Java
        run: |
          mkdir out
          javac -d out src/*.java

      - name: Package JAR
        run: |
          jar --create --file app.jar --main-class Main -C out .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: app.jar
